# Generated by Django 6.0.6 on 2026-06-26 03:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('circulation', '0002_seed_borrowing_policies'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='catalog.book')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='catalog.bookcopy')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamagedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_date', models.DateField(default=django.utils.timezone.localdate)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=30)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('sent_repair', 'Sent to Repair'), ('repaired', 'Repaired'), ('written_off', 'Written Off')], default='reported', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='catalog.bookcopy')),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='circulation.borrowrecord')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_books', to='members.member')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damaged_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='LostBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_date', models.DateField(default=django.utils.timezone.localdate)),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('charged', 'Charged'), ('paid', 'Paid'), ('replaced', 'Replaced'), ('recovered', 'Recovered'), ('written_off', 'Written Off')], default='reported', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_records', to='catalog.bookcopy')),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_records', to='circulation.borrowrecord')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_books', to='members.member')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('sent_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('under_repair', 'Under Repair'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='under_repair', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_records', to='catalog.bookcopy')),
                ('damage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_records', to='status_tracking.damagedbook')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_repair_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-sent_date'],
            },
        ),
    ]
