# Generated by Django 6.0.6 on 2026-07-01 16:11

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_terminal_status_dates(apps, schema_editor):
    today = django.utils.timezone.localdate()
    DamagedBook = apps.get_model("status_tracking", "DamagedBook")
    LostBook = apps.get_model("status_tracking", "LostBook")
    RepairRecord = apps.get_model("status_tracking", "RepairRecord")

    DamagedBook.objects.filter(
        status__in=["repaired", "written_off"],
        resolved_date__isnull=True,
    ).update(resolved_date=today)
    DamagedBook.objects.filter(
        status__in=["reported", "under_review", "sent_repair"],
        resolved_date__isnull=False,
    ).update(resolved_date=None)

    LostBook.objects.filter(
        status__in=["replaced", "recovered", "written_off"],
        resolved_date__isnull=True,
    ).update(resolved_date=today)
    LostBook.objects.filter(
        status__in=["reported", "charged", "paid"],
        resolved_date__isnull=False,
    ).update(resolved_date=None)

    RepairRecord.objects.filter(
        status="completed",
        completed_date__isnull=True,
    ).update(completed_date=today)
    RepairRecord.objects.filter(
        status__in=["under_repair", "cancelled"],
        completed_date__isnull=False,
    ).update(completed_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_booklocation_unique_together_and_more'),
        ('circulation', '0003_alter_reservation_options_and_more'),
        ('members', '0002_alter_member_emergency_contact_phone_and_more'),
        ('status_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedbook',
            name='resolved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookstatuslog',
            name='new_status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], max_length=30),
        ),
        migrations.AlterField(
            model_name='damagedbook',
            name='estimated_repair_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lostbook',
            name='replacement_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='repairrecord',
            name='repair_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(backfill_terminal_status_dates, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='bookstatuslog',
            index=models.Index(fields=['book_copy', 'created_at'], name='status_trac_book_co_15540b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookstatuslog',
            index=models.Index(fields=['new_status', 'created_at'], name='status_trac_new_sta_ba2ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedbook',
            index=models.Index(fields=['book_copy', 'status'], name='status_trac_book_co_d6ab42_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedbook',
            index=models.Index(fields=['member', 'status'], name='status_trac_member__0c98af_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedbook',
            index=models.Index(fields=['severity', 'status'], name='status_trac_severit_ed8b94_idx'),
        ),
        migrations.AddIndex(
            model_name='lostbook',
            index=models.Index(fields=['book_copy', 'status'], name='status_trac_book_co_c6237d_idx'),
        ),
        migrations.AddIndex(
            model_name='lostbook',
            index=models.Index(fields=['member', 'status'], name='status_trac_member__b9eb06_idx'),
        ),
        migrations.AddIndex(
            model_name='lostbook',
            index=models.Index(fields=['reported_date'], name='status_trac_reporte_6fc44c_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrecord',
            index=models.Index(fields=['book_copy', 'status'], name='status_trac_book_co_883ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrecord',
            index=models.Index(fields=['sent_date'], name='status_trac_sent_da_ea8059_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrecord',
            index=models.Index(fields=['expected_return_date'], name='status_trac_expecte_43b033_idx'),
        ),
        migrations.AddConstraint(
            model_name='damagedbook',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_repair_cost__gte', 0)), name='damaged_estimated_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='damagedbook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_date__isnull', False), ('status__in', ['repaired', 'written_off'])), models.Q(('resolved_date__isnull', True), ('status__in', ['reported', 'under_review', 'sent_repair'])), _connector='OR'), name='damaged_status_matches_resolved_date'),
        ),
        migrations.AddConstraint(
            model_name='damagedbook',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reported', 'under_review', 'sent_repair'])), fields=('book_copy',), name='one_open_damage_record_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='lostbook',
            constraint=models.CheckConstraint(condition=models.Q(('replacement_cost__gte', 0)), name='lost_replacement_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lostbook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_date__isnull', False), ('status__in', ['replaced', 'recovered', 'written_off'])), models.Q(('resolved_date__isnull', True), ('status__in', ['reported', 'charged', 'paid'])), _connector='OR'), name='lost_status_matches_resolved_date'),
        ),
        migrations.AddConstraint(
            model_name='lostbook',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reported', 'charged', 'paid'])), fields=('book_copy',), name='one_open_lost_record_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='repairrecord',
            constraint=models.CheckConstraint(condition=models.Q(('repair_cost__gte', 0)), name='repair_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='repairrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_date__isnull', False), ('status', 'completed')), models.Q(('completed_date__isnull', True), ('status__in', ['under_repair', 'cancelled'])), _connector='OR'), name='repair_status_matches_completed_date'),
        ),
        migrations.AddConstraint(
            model_name='repairrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'under_repair')), fields=('book_copy',), name='one_open_repair_record_per_copy'),
        ),
    ]
