# Generated by Django 6.0.6 on 2026-06-29 10:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, parentheses, +, or -.', regex='^\\+?[0-9][0-9 ()-]{6,24}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_code',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, parentheses, +, or -.', regex='^\\+?[0-9][0-9 ()-]{6,24}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, parentheses, +, or -.', regex='^\\+?[0-9][0-9 ()-]{6,24}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_type', 'status'], name='members_mem_member__c3d4f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gte', models.F('joined_date')), _connector='OR'), name='member_expiry_on_or_after_joined'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('year_level__gte', 1), ('year_level__lte', 8)), name='student_year_level_between_1_and_8'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('semester__gte', 1), ('semester__lte', 3)), name='student_semester_between_1_and_3'),
        ),
    ]
