# Generated by Django 6.0.6 on 2026-06-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_phase7_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('accounts', 'Authentication and Users'), ('members', 'Members'), ('catalog', 'Books and Catalog'), ('circulation', 'Borrowing and Returning'), ('fines', 'Fines and Payments'), ('notifications', 'Notifications'), ('status_tracking', 'Book Status Tracking'), ('dashboard', 'Dashboard'), ('reports', 'Reports and Analytics'), ('activity', 'Activity and Audit Logs'), ('digital', 'Digital Library'), ('reviews', 'Book Reviews'), ('announcements', 'Announcements'), ('support', 'Help and Support'), ('settings', 'System Settings'), ('import_export', 'Import and Export')], max_length=50),
        ),
    ]
