# Generated by Django 6.0.6 on 2026-06-30 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Sum
from django.utils import timezone


def normalize_financial_history(apps, schema_editor):
    Fine = apps.get_model('fines', 'Fine')
    Payment = apps.get_model('fines', 'Payment')
    database = schema_editor.connection.alias
    now = timezone.now()
    today = now.date()

    invalid_payments = Payment.objects.using(database).filter(amount_paid__lte=0)
    invalid_payments.update(
        amount_paid=Decimal('0.01'),
        status='voided',
        voided_at=now,
        void_reason='Migrated invalid non-positive payment.',
    )
    Payment.objects.using(database).filter(payment_date__gt=today).update(
        payment_date=today
    )

    duplicate_groups = (
        Fine.objects.using(database)
        .filter(reason='late_return', borrow_record__isnull=False)
        .values('borrow_record_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    for group in duplicate_groups.iterator():
        duplicates = list(
            Fine.objects.using(database)
            .filter(
                borrow_record_id=group['borrow_record_id'],
                reason='late_return',
            )
            .order_by('created_at', 'pk')
        )
        survivor = duplicates[0]
        duplicate_ids = [fine.pk for fine in duplicates[1:]]
        Payment.objects.using(database).filter(fine_id__in=duplicate_ids).update(
            fine_id=survivor.pk,
            member_id=survivor.member_id,
        )
        survivor.amount = max(fine.amount for fine in duplicates)
        survivor.save(using=database, update_fields=['amount'])
        Fine.objects.using(database).filter(pk__in=duplicate_ids).delete()

    for fine in Fine.objects.using(database).select_related('borrow_record').iterator():
        member_id = fine.member_id
        if fine.borrow_record_id:
            member_id = fine.borrow_record.member_id
        Payment.objects.using(database).filter(fine_id=fine.pk).update(member_id=member_id)
        paid_total = (
            Payment.objects.using(database)
            .filter(fine_id=fine.pk, status='completed')
            .aggregate(total=Sum('amount_paid'))['total']
            or Decimal('0.00')
        )
        amount = fine.amount if fine.amount > 0 else Decimal('0.01')
        amount = max(amount, paid_total)
        updates = {
            'member_id': member_id,
            'amount': amount,
            'paid_amount': paid_total,
            'updated_by_id': fine.created_by_id,
        }
        if fine.status == 'waived':
            updates.update(
                status='waived',
                waived_at=fine.updated_at or now,
                waiver_reason='Legacy waiver migrated to the audited workflow.',
            )
        elif paid_total <= Decimal('0.00'):
            updates.update(status='unpaid', waived_at=None, waiver_reason='')
        elif paid_total < amount:
            updates.update(status='partial', waived_at=None, waiver_reason='')
        else:
            updates.update(status='paid', waived_at=None, waiver_reason='')
        Fine.objects.using(database).filter(pk=fine.pk).update(**updates)


def grant_member_payment_history(apps, schema_editor):
    Permission = apps.get_model('accounts', 'Permission')
    Role = apps.get_model('accounts', 'Role')
    try:
        permission = Permission.objects.get(codename='fines.view_payment')
    except Permission.DoesNotExist:
        return
    for slug in ('student', 'teacher', 'staff'):
        role = Role.objects.filter(slug=slug).first()
        if role:
            role.permissions.add(permission)


def revoke_member_payment_history(apps, schema_editor):
    Permission = apps.get_model('accounts', 'Permission')
    Role = apps.get_model('accounts', 'Role')
    permission = Permission.objects.filter(codename='fines.view_payment').first()
    if not permission:
        return
    for role in Role.objects.filter(slug__in=('student', 'teacher', 'staff')):
        role.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_avatar'),
        ('circulation', '0003_alter_reservation_options_and_more'),
        ('fines', '0001_initial'),
        ('members', '0002_alter_member_emergency_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='waiver_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_fine_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fine',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fine_payments', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['member', 'status'], name='fines_fine_member__c477d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['reason', 'status'], name='fines_fine_reason_5322a2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['member', 'payment_date'], name='fines_payme_member__6cab8e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fine', 'status'], name='fines_payme_fine_id_dbe986_idx'),
        ),
        migrations.RunPython(normalize_financial_history, migrations.RunPython.noop),
        migrations.RunPython(grant_member_payment_history, revoke_member_payment_history),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fine_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('paid_amount__lte', models.F('amount'))), name='fine_paid_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_amount', 0), ('status', 'unpaid'), ('waived_at__isnull', True)), models.Q(('paid_amount__gt', 0), ('status', 'partial'), ('waived_at__isnull', True), ('paid_amount__lt', models.F('amount'))), models.Q(('paid_amount', models.F('amount')), ('status', 'paid'), ('waived_at__isnull', True)), models.Q(('status', 'waived'), ('waived_at__isnull', False), models.Q(('waiver_reason', ''), _negated=True)), _connector='OR'), name='fine_status_matches_accounting'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.UniqueConstraint(condition=models.Q(('borrow_record__isnull', False), ('reason', 'late_return')), fields=('borrow_record',), name='one_late_fine_per_borrow'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), ('void_reason', ''), ('voided_at__isnull', True)), models.Q(('status', 'voided'), ('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='payment_status_matches_void'),
        ),
    ]
