# Generated by Django 6.0.6 on 2026-06-30 10:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_circulation_history(apps, schema_editor):
    """Backfill immutable loan rates and normalize the reservation lifecycle."""
    BorrowRecord = apps.get_model('circulation', 'BorrowRecord')
    BorrowingPolicy = apps.get_model('circulation', 'BorrowingPolicy')
    Reservation = apps.get_model('circulation', 'Reservation')
    database = schema_editor.connection.alias

    policy_rates = dict(
        BorrowingPolicy.objects.using(database).values_list('member_type', 'fine_per_day')
    )
    loans = BorrowRecord.objects.using(database).select_related('member')
    for loan in loans.iterator():
        rate = policy_rates.get(loan.member.member_type, Decimal('1.00'))
        BorrowRecord.objects.using(database).filter(pk=loan.pk).update(
            fine_rate_per_day=rate
        )

    Reservation.objects.using(database).filter(status='pending').update(
        ready_date=None,
        expiry_date=None,
    )
    for reservation in Reservation.objects.using(database).filter(status='ready').iterator():
        reservation.ready_date = reservation.reserved_date
        if reservation.expiry_date is None:
            reservation.expiry_date = reservation.reserved_date
        reservation.save(
            using=database,
            update_fields=['ready_date', 'expiry_date'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_booklocation_unique_together_and_more'),
        ('circulation', '0002_seed_borrowing_policies'),
        ('members', '0002_alter_member_emergency_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['status', 'reserved_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_rate_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ready_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='borrowingpolicy',
            name='fine_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='borrowingpolicy',
            name='loan_period_days',
            field=models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='borrowingpolicy',
            name='max_books',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='borrowingpolicy',
            name='renewal_days',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='borrowingpolicy',
            name='reservation_expiry_days',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='renewal_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='borrowed', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='renewalrecord',
            name='borrow_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='circulation.borrowrecord'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(migrate_circulation_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='borrowingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('max_books__gte', 1)), name='policy_max_books_positive'),
        ),
        migrations.AddConstraint(
            model_name='borrowingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('loan_period_days__gte', 1)), name='policy_loan_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='borrowingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_days__gte', 1)), name='policy_renewal_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='borrowingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('fine_per_day__gte', 0)), name='policy_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='borrowingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_expiry_days__gte', 1)), name='policy_reservation_expiry_positive'),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('borrow_date'))), name='borrow_due_on_or_after_borrow'),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(('return_date__isnull', True), ('return_date__gte', models.F('borrow_date')), _connector='OR'), name='borrow_return_on_or_after_borrow'),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(('fine_rate_per_day__gte', 0)), name='borrow_fine_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['borrowed', 'overdue'])), fields=('book_copy',), name='one_active_borrow_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='renewalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('new_due_date__gt', models.F('old_due_date'))), name='renewal_new_due_after_old_due'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gte', models.F('reserved_date')), _connector='OR'), name='reservation_expiry_on_or_after_reserved'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('ready_date__isnull', True), ('ready_date__gte', models.F('reserved_date')), _connector='OR'), name='reservation_ready_on_or_after_reserved'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'ready'])), fields=('member', 'book'), name='one_active_reservation_per_member_book'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ready')), fields=('book',), name='one_ready_reservation_per_book'),
        ),
        migrations.AddConstraint(
            model_name='returnrecord',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='return_fine_non_negative'),
        ),
    ]
