# Generated by Django 6.0.6 on 2026-06-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_dashboard_reports_activity_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('accounts', 'Authentication and Users'), ('members', 'Members'), ('catalog', 'Books and Catalog'), ('circulation', 'Borrowing and Returning'), ('fines', 'Fines and Payments'), ('notifications', 'Notifications'), ('status_tracking', 'Book Status Tracking'), ('dashboard', 'Dashboard'), ('reports', 'Reports and Analytics'), ('activity', 'Activity and Audit Logs'), ('settings', 'System Settings')], max_length=50),
        ),
    ]
