# Generated by Django 6.0.6 on 2026-07-01 10:34

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def normalize_notification_history(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    EmailReminder = apps.get_model('notifications', 'EmailReminder')
    database = schema_editor.connection.alias
    now = timezone.now()

    attempts = {}
    reminders = EmailReminder.objects.using(database).select_related(
        'notification', 'borrow_record'
    ).order_by('notification_id', 'created_at', 'pk')
    for reminder in reminders.iterator():
        if reminder.notification_id:
            attempts[reminder.notification_id] = attempts.get(reminder.notification_id, 0) + 1
            attempt_number = attempts[reminder.notification_id]
            member_id = reminder.notification.recipient_id
        else:
            attempt_number = 1
            member_id = reminder.member_id
        if reminder.borrow_record_id:
            member_id = reminder.borrow_record.member_id
        attempted_at = reminder.sent_at or reminder.created_at or now
        if reminder.status == 'sent':
            sent_at = reminder.sent_at or attempted_at
            error_message = ''
        else:
            sent_at = None
            error_message = reminder.error_message or 'Legacy email delivery failed.'
        EmailReminder.objects.using(database).filter(pk=reminder.pk).update(
            member_id=member_id,
            attempt_number=attempt_number,
            attempted_at=attempted_at,
            sent_at=sent_at,
            error_message=error_message,
        )

    notifications = Notification.objects.using(database).select_related(
        'related_borrow_record'
    )
    for notification in notifications.iterator():
        recipient_id = notification.recipient_id
        book_copy_id = notification.related_book_copy_id
        if notification.related_borrow_record_id:
            recipient_id = notification.related_borrow_record.member_id
            book_copy_id = notification.related_borrow_record.book_copy_id

        read_at = notification.read_at
        archived_at = None
        if notification.status == 'unread':
            read_at = None
        elif notification.status == 'read':
            read_at = read_at or notification.updated_at or now
        else:
            archived_at = notification.updated_at or now

        sent_log = (
            EmailReminder.objects.using(database)
            .filter(notification_id=notification.pk, status='sent')
            .order_by('-sent_at', '-pk')
            .first()
        )
        is_email_sent = bool(sent_log) or bool(
            notification.is_email_sent and notification.email_sent_at
        )
        email_sent_at = (
            sent_log.sent_at
            if sent_log
            else notification.email_sent_at if is_email_sent else None
        )
        Notification.objects.using(database).filter(pk=notification.pk).update(
            recipient_id=recipient_id,
            related_book_copy_id=book_copy_id,
            read_at=read_at,
            archived_at=archived_at,
            is_email_sent=is_email_sent,
            email_sent_at=email_sent_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_booklocation_unique_together_and_more'),
        ('circulation', '0003_alter_reservation_options_and_more'),
        ('members', '0002_alter_member_emergency_contact_phone_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailreminder',
            options={'ordering': ['-attempted_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='emailreminder',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='emailreminder',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailreminder',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailreminder',
            name='error_message',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emailreminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='emailreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', editable=False, max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailreminder',
            index=models.Index(fields=['member', 'status'], name='notificatio_member__b1f607_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreminder',
            index=models.Index(fields=['status', 'attempted_at'], name='notificatio_status_d23bb3_idx'),
        ),
        migrations.RunPython(normalize_notification_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='emailreminder',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='email_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='emailreminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error_message', ''), ('sent_at__isnull', True), ('status', 'pending')), models.Q(('error_message', ''), ('sent_at__isnull', False), ('status', 'sent')), models.Q(('sent_at__isnull', True), ('status', 'failed'), models.Q(('error_message', ''), _negated=True)), _connector='OR'), name='email_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='emailreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('notification__isnull', False)), fields=('notification', 'attempt_number'), name='unique_email_attempt_per_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('read_at__isnull', True), ('status', 'unread')), models.Q(('archived_at__isnull', True), ('read_at__isnull', False), ('status', 'read')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='notification_status_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email_sent_at__isnull', True), ('is_email_sent', False)), models.Q(('email_sent_at__isnull', False), ('is_email_sent', True)), _connector='OR'), name='notification_email_flag_valid'),
        ),
    ]
