# Generated by Django 6.0.6 on 2026-06-25 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('member_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('librarian', 'Librarian'), ('assistant_librarian', 'Assistant Librarian')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member_code', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='LibrarianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('librarian_id', models.CharField(max_length=50, unique=True)),
                ('employee_type', models.CharField(choices=[('librarian', 'Librarian'), ('assistant_librarian', 'Assistant Librarian')], max_length=30)),
                ('department', models.CharField(default='Library', max_length=120)),
                ('shift', models.CharField(blank=True, max_length=80)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('can_approve_overrides', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_profile', to='members.member')),
            ],
            options={
                'ordering': ['librarian_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('office', models.CharField(blank=True, max_length=120)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='members.member')),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('program', models.CharField(blank=True, max_length=120)),
                ('year_level', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='members.member')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('faculty', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('office', models.CharField(blank=True, max_length=120)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='members.member')),
            ],
            options={
                'ordering': ['teacher_id'],
            },
        ),
    ]
