# Generated by Django 6.0.6 on 2026-06-29 11:29

import apps.catalog.models
import django.core.validators
import django.db.models.functions.text
import re
from django.conf import settings
from django.db import migrations, models


def normalize_catalog_identifiers(apps, schema_editor):
    Book = apps.get_model("catalog", "Book")
    BookCopy = apps.get_model("catalog", "BookCopy")
    Category = apps.get_model("catalog", "Category")
    Shelf = apps.get_model("catalog", "Shelf")
    Publisher = apps.get_model("catalog", "Publisher")
    BookLocation = apps.get_model("catalog", "BookLocation")

    specifications = [
        (Book, "book_code", lambda value: value.strip().upper()),
        (Book, "isbn", lambda value: re.sub(r"[-\s]", "", value).upper()),
        (BookCopy, "copy_code", lambda value: value.strip().upper()),
        (BookCopy, "barcode", lambda value: value.strip().upper()),
        (Category, "code", lambda value: value.strip().upper()),
        (Shelf, "shelf_code", lambda value: value.strip().upper()),
        (Publisher, "name", lambda value: value.strip()),
    ]
    for model, field, normalizer in specifications:
        rows = list(model.objects.exclude(**{f"{field}__isnull": True}).values_list("pk", field))
        normalized = {}
        for pk, value in rows:
            if value in (None, ""):
                continue
            new_value = normalizer(value)
            collision_key = new_value.casefold()
            if collision_key in normalized and normalized[collision_key] != pk:
                raise RuntimeError(
                    f"Cannot normalize catalog.{model._meta.model_name}.{field}; "
                    f"duplicate value: {new_value}"
                )
            normalized[collision_key] = pk
        for pk, value in rows:
            if value not in (None, ""):
                model.objects.filter(pk=pk).update(**{field: normalizer(value)})

    seen_locations = {}
    for pk, shelf_id, label in BookLocation.objects.values_list("pk", "shelf_id", "label"):
        normalized_label = label.strip()
        key = (shelf_id, normalized_label.casefold())
        if key in seen_locations:
            raise RuntimeError(
                f"Cannot normalize catalog.booklocation.label; duplicate label on shelf: {normalized_label}"
            )
        seen_locations[key] = pk
        BookLocation.objects.filter(pk=pk).update(label=normalized_label)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booklocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='authors/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.catalog.models.validate_catalog_image_size]),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.catalog.models.validate_catalog_image_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.catalog.models.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='available', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_code',
            field=models.CharField(blank=True, editable=False, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='qr_code',
            field=models.FileField(blank=True, editable=False, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair')], default='available', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, parentheses, +, or -.', regex='^\\+?[0-9][0-9 ()-]{6,24}$')]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='catalog_aut_name_dfdf17_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='catalog_boo_status_b30b19_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status'], name='catalog_boo_status_da6f38_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['acquired_date'], name='catalog_boo_acquire_f614a9_idx'),
        ),
        migrations.RunPython(normalize_catalog_identifiers, noop_reverse),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('book_code'), name='book_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('pages__isnull', True), ('pages__gte', 1), _connector='OR'), name='book_pages_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('copy_code'), name='copy_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('barcode'), name='barcode_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='book_copy_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booklocation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('shelf'), name='location_label_per_shelf_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='category_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='publisher_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shelf_code'), name='shelf_code_ci_unique'),
        ),
    ]
